# Global Makefile properties

# Build tools
CC	= gcc
AS	= as

# ELF tools
OBJCOPY	= objcopy
OBJDUMP	= objdump
READELF	= readelf

#MISC TOOLS
SED	= sed

# Path to Metasploit Framework (adjust if necessary)
MSFHOME	= ~/metasploit

